# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: domain.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='domain.proto',
  package='io.spoud.sdm.logistics.domain.v1',
  syntax='proto3',
  serialized_options=_b('\n io.spoud.sdm.logistics.domain.v1P\001Z\023logistics.domain.v1'),
  serialized_pb=_b('\n\x0c\x64omain.proto\x12 io.spoud.sdm.logistics.domain.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"M\n\nActionInfo\x12\x10\n\x08username\x18\x01 \x01(\t\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x8d\x01\n\x07\x44ocInfo\x12=\n\x07\x63reated\x18\x01 \x01(\x0b\x32,.io.spoud.sdm.logistics.domain.v1.ActionInfo\x12\x43\n\rlast_modified\x18\x02 \x01(\x0b\x32,.io.spoud.sdm.logistics.domain.v1.ActionInfo\"1\n\x0fIdNameReference\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\tJ\x04\x08\n\x10\x0b\"\x1f\n\x0bIdReference\x12\n\n\x02id\x18\x01 \x01(\tJ\x04\x08\n\x10\x0b\"\xc1\x02\n\rResourceGroup\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x44\n\ttransport\x18\x03 \x01(\x0b\x32\x31.io.spoud.sdm.logistics.domain.v1.IdNameReference\x12\x0f\n\x07\x64\x65\x66\x61ult\x18\x04 \x01(\x08\x12S\n\nproperties\x18\x05 \x03(\x0b\x32?.io.spoud.sdm.logistics.domain.v1.ResourceGroup.PropertiesEntry\x12\x37\n\x04info\x18\x06 \x01(\x0b\x32).io.spoud.sdm.logistics.domain.v1.DocInfo\x1a\x31\n\x0fPropertiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x39\n io.spoud.sdm.logistics.domain.v1P\x01Z\x13logistics.domain.v1b\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_ACTIONINFO = _descriptor.Descriptor(
  name='ActionInfo',
  full_name='io.spoud.sdm.logistics.domain.v1.ActionInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='io.spoud.sdm.logistics.domain.v1.ActionInfo.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='io.spoud.sdm.logistics.domain.v1.ActionInfo.timestamp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=160,
)


_DOCINFO = _descriptor.Descriptor(
  name='DocInfo',
  full_name='io.spoud.sdm.logistics.domain.v1.DocInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='created', full_name='io.spoud.sdm.logistics.domain.v1.DocInfo.created', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_modified', full_name='io.spoud.sdm.logistics.domain.v1.DocInfo.last_modified', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=304,
)


_IDNAMEREFERENCE = _descriptor.Descriptor(
  name='IdNameReference',
  full_name='io.spoud.sdm.logistics.domain.v1.IdNameReference',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='io.spoud.sdm.logistics.domain.v1.IdNameReference.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='io.spoud.sdm.logistics.domain.v1.IdNameReference.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=306,
  serialized_end=355,
)


_IDREFERENCE = _descriptor.Descriptor(
  name='IdReference',
  full_name='io.spoud.sdm.logistics.domain.v1.IdReference',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='io.spoud.sdm.logistics.domain.v1.IdReference.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=357,
  serialized_end=388,
)


_RESOURCEGROUP_PROPERTIESENTRY = _descriptor.Descriptor(
  name='PropertiesEntry',
  full_name='io.spoud.sdm.logistics.domain.v1.ResourceGroup.PropertiesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='io.spoud.sdm.logistics.domain.v1.ResourceGroup.PropertiesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='io.spoud.sdm.logistics.domain.v1.ResourceGroup.PropertiesEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=663,
  serialized_end=712,
)

_RESOURCEGROUP = _descriptor.Descriptor(
  name='ResourceGroup',
  full_name='io.spoud.sdm.logistics.domain.v1.ResourceGroup',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='io.spoud.sdm.logistics.domain.v1.ResourceGroup.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='io.spoud.sdm.logistics.domain.v1.ResourceGroup.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='transport', full_name='io.spoud.sdm.logistics.domain.v1.ResourceGroup.transport', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='default', full_name='io.spoud.sdm.logistics.domain.v1.ResourceGroup.default', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='properties', full_name='io.spoud.sdm.logistics.domain.v1.ResourceGroup.properties', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='info', full_name='io.spoud.sdm.logistics.domain.v1.ResourceGroup.info', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_RESOURCEGROUP_PROPERTIESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=391,
  serialized_end=712,
)

_ACTIONINFO.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_DOCINFO.fields_by_name['created'].message_type = _ACTIONINFO
_DOCINFO.fields_by_name['last_modified'].message_type = _ACTIONINFO
_RESOURCEGROUP_PROPERTIESENTRY.containing_type = _RESOURCEGROUP
_RESOURCEGROUP.fields_by_name['transport'].message_type = _IDNAMEREFERENCE
_RESOURCEGROUP.fields_by_name['properties'].message_type = _RESOURCEGROUP_PROPERTIESENTRY
_RESOURCEGROUP.fields_by_name['info'].message_type = _DOCINFO
DESCRIPTOR.message_types_by_name['ActionInfo'] = _ACTIONINFO
DESCRIPTOR.message_types_by_name['DocInfo'] = _DOCINFO
DESCRIPTOR.message_types_by_name['IdNameReference'] = _IDNAMEREFERENCE
DESCRIPTOR.message_types_by_name['IdReference'] = _IDREFERENCE
DESCRIPTOR.message_types_by_name['ResourceGroup'] = _RESOURCEGROUP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ActionInfo = _reflection.GeneratedProtocolMessageType('ActionInfo', (_message.Message,), {
  'DESCRIPTOR' : _ACTIONINFO,
  '__module__' : 'domain_pb2'
  # @@protoc_insertion_point(class_scope:io.spoud.sdm.logistics.domain.v1.ActionInfo)
  })
_sym_db.RegisterMessage(ActionInfo)

DocInfo = _reflection.GeneratedProtocolMessageType('DocInfo', (_message.Message,), {
  'DESCRIPTOR' : _DOCINFO,
  '__module__' : 'domain_pb2'
  # @@protoc_insertion_point(class_scope:io.spoud.sdm.logistics.domain.v1.DocInfo)
  })
_sym_db.RegisterMessage(DocInfo)

IdNameReference = _reflection.GeneratedProtocolMessageType('IdNameReference', (_message.Message,), {
  'DESCRIPTOR' : _IDNAMEREFERENCE,
  '__module__' : 'domain_pb2'
  # @@protoc_insertion_point(class_scope:io.spoud.sdm.logistics.domain.v1.IdNameReference)
  })
_sym_db.RegisterMessage(IdNameReference)

IdReference = _reflection.GeneratedProtocolMessageType('IdReference', (_message.Message,), {
  'DESCRIPTOR' : _IDREFERENCE,
  '__module__' : 'domain_pb2'
  # @@protoc_insertion_point(class_scope:io.spoud.sdm.logistics.domain.v1.IdReference)
  })
_sym_db.RegisterMessage(IdReference)

ResourceGroup = _reflection.GeneratedProtocolMessageType('ResourceGroup', (_message.Message,), {

  'PropertiesEntry' : _reflection.GeneratedProtocolMessageType('PropertiesEntry', (_message.Message,), {
    'DESCRIPTOR' : _RESOURCEGROUP_PROPERTIESENTRY,
    '__module__' : 'domain_pb2'
    # @@protoc_insertion_point(class_scope:io.spoud.sdm.logistics.domain.v1.ResourceGroup.PropertiesEntry)
    })
  ,
  'DESCRIPTOR' : _RESOURCEGROUP,
  '__module__' : 'domain_pb2'
  # @@protoc_insertion_point(class_scope:io.spoud.sdm.logistics.domain.v1.ResourceGroup)
  })
_sym_db.RegisterMessage(ResourceGroup)
_sym_db.RegisterMessage(ResourceGroup.PropertiesEntry)


DESCRIPTOR._options = None
_RESOURCEGROUP_PROPERTIESENTRY._options = None
# @@protoc_insertion_point(module_scope)
