# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import logistics_pb2 as logistics__pb2
import resource_group_pb2 as resource__group__pb2


class LogisticsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateOffer = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/CreateOffer',
        request_serializer=logistics__pb2.CreateDataOfferRequest.SerializeToString,
        response_deserializer=logistics__pb2.CreateDataOfferResponse.FromString,
        )
    self.DeleteOffer = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/DeleteOffer',
        request_serializer=logistics__pb2.DeleteDataOfferRequest.SerializeToString,
        response_deserializer=logistics__pb2.DeleteDataOfferResponse.FromString,
        )
    self.GetOffer = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/GetOffer',
        request_serializer=logistics__pb2.GetDataOfferRequest.SerializeToString,
        response_deserializer=logistics__pb2.GetDataOfferResponse.FromString,
        )
    self.ListOffers = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/ListOffers',
        request_serializer=logistics__pb2.ListDataOffersRequest.SerializeToString,
        response_deserializer=logistics__pb2.ListDataOffersResponse.FromString,
        )
    self.UpdateOffer = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/UpdateOffer',
        request_serializer=logistics__pb2.UpdateDataOfferRequest.SerializeToString,
        response_deserializer=logistics__pb2.UpdateDataOfferResponse.FromString,
        )
    self.SearchDataOffers = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/SearchDataOffers',
        request_serializer=logistics__pb2.SearchDataOffersRequest.SerializeToString,
        response_deserializer=logistics__pb2.SearchDataOffersResponse.FromString,
        )
    self.CreateSubscription = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/CreateSubscription',
        request_serializer=logistics__pb2.CreateDataSubscriptionRequest.SerializeToString,
        response_deserializer=logistics__pb2.CreateDataSubscriptionResponse.FromString,
        )
    self.DeleteSubscription = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/DeleteSubscription',
        request_serializer=logistics__pb2.DeleteDataSubscriptionRequest.SerializeToString,
        response_deserializer=logistics__pb2.DeleteDataSubscriptionResponse.FromString,
        )
    self.GetSubscription = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/GetSubscription',
        request_serializer=logistics__pb2.GetDataSubscriptionRequest.SerializeToString,
        response_deserializer=logistics__pb2.GetDataSubscriptionResponse.FromString,
        )
    self.ListSubscriptions = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/ListSubscriptions',
        request_serializer=logistics__pb2.ListDataSubscriptionsRequest.SerializeToString,
        response_deserializer=logistics__pb2.ListDataSubscriptionsResponse.FromString,
        )
    self.UpdateSubscription = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/UpdateSubscription',
        request_serializer=logistics__pb2.UpdateDataSubscriptionRequest.SerializeToString,
        response_deserializer=logistics__pb2.UpdateDataSubscriptionResponse.FromString,
        )
    self.CreateConnector = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/CreateConnector',
        request_serializer=logistics__pb2.CreateConnectorRequest.SerializeToString,
        response_deserializer=logistics__pb2.CreateConnectorResponse.FromString,
        )
    self.DeleteConnector = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/DeleteConnector',
        request_serializer=logistics__pb2.DeleteConnectorRequest.SerializeToString,
        response_deserializer=logistics__pb2.DeleteConnectorResponse.FromString,
        )
    self.GetConnector = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/GetConnector',
        request_serializer=logistics__pb2.GetConnectorRequest.SerializeToString,
        response_deserializer=logistics__pb2.GetConnectorResponse.FromString,
        )
    self.ListConnectors = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/ListConnectors',
        request_serializer=logistics__pb2.ListConnectorsRequest.SerializeToString,
        response_deserializer=logistics__pb2.ListConnectorsResponse.FromString,
        )
    self.UpdateConnector = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/UpdateConnector',
        request_serializer=logistics__pb2.UpdateConnectorRequest.SerializeToString,
        response_deserializer=logistics__pb2.UpdateConnectorResponse.FromString,
        )
    self.CreateGroup = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/CreateGroup',
        request_serializer=logistics__pb2.CreateGroupRequest.SerializeToString,
        response_deserializer=logistics__pb2.CreateGroupResponse.FromString,
        )
    self.DeleteGroup = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/DeleteGroup',
        request_serializer=logistics__pb2.DeleteGroupRequest.SerializeToString,
        response_deserializer=logistics__pb2.DeleteGroupResponse.FromString,
        )
    self.GetGroup = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/GetGroup',
        request_serializer=logistics__pb2.GetGroupRequest.SerializeToString,
        response_deserializer=logistics__pb2.GetGroupResponse.FromString,
        )
    self.ListGroups = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/ListGroups',
        request_serializer=logistics__pb2.ListGroupsRequest.SerializeToString,
        response_deserializer=logistics__pb2.ListGroupsResponse.FromString,
        )
    self.UpdateGroup = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/UpdateGroup',
        request_serializer=logistics__pb2.UpdateGroupRequest.SerializeToString,
        response_deserializer=logistics__pb2.UpdateGroupResponse.FromString,
        )
    self.CreateOfferTemplate = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/CreateOfferTemplate',
        request_serializer=logistics__pb2.CreateDataOfferTemplateRequest.SerializeToString,
        response_deserializer=logistics__pb2.CreateDataOfferTemplateResponse.FromString,
        )
    self.DeleteOfferTemplate = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/DeleteOfferTemplate',
        request_serializer=logistics__pb2.DeleteDataOfferTemplateRequest.SerializeToString,
        response_deserializer=logistics__pb2.DeleteDataOfferTemplateResponse.FromString,
        )
    self.GetOfferTemplate = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/GetOfferTemplate',
        request_serializer=logistics__pb2.GetDataOfferTemplateRequest.SerializeToString,
        response_deserializer=logistics__pb2.GetDataOfferTemplateResponse.FromString,
        )
    self.ListOfferTemplates = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/ListOfferTemplates',
        request_serializer=logistics__pb2.ListDataOfferTemplatesRequest.SerializeToString,
        response_deserializer=logistics__pb2.ListDataOfferTemplatesResponse.FromString,
        )
    self.UpdateOfferTemplate = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/UpdateOfferTemplate',
        request_serializer=logistics__pb2.UpdateDataOfferTemplateRequest.SerializeToString,
        response_deserializer=logistics__pb2.UpdateDataOfferTemplateResponse.FromString,
        )
    self.CreateSubscriptionTemplate = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/CreateSubscriptionTemplate',
        request_serializer=logistics__pb2.CreateDataSubscriptionTemplateRequest.SerializeToString,
        response_deserializer=logistics__pb2.CreateDataSubscriptionTemplateResponse.FromString,
        )
    self.DeleteSubscriptionTemplate = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/DeleteSubscriptionTemplate',
        request_serializer=logistics__pb2.DeleteDataSubscriptionTemplateRequest.SerializeToString,
        response_deserializer=logistics__pb2.DeleteDataSubscriptionTemplateResponse.FromString,
        )
    self.GetSubscriptionTemplate = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/GetSubscriptionTemplate',
        request_serializer=logistics__pb2.GetDataSubscriptionTemplateRequest.SerializeToString,
        response_deserializer=logistics__pb2.GetDataSubscriptionTemplateResponse.FromString,
        )
    self.ListSubscriptionTemplates = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/ListSubscriptionTemplates',
        request_serializer=logistics__pb2.ListDataSubscriptionTemplatesRequest.SerializeToString,
        response_deserializer=logistics__pb2.ListDataSubscriptionTemplatesResponse.FromString,
        )
    self.UpdateSubscriptionTemplate = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/UpdateSubscriptionTemplate',
        request_serializer=logistics__pb2.UpdateDataSubscriptionTemplateRequest.SerializeToString,
        response_deserializer=logistics__pb2.UpdateDataSubscriptionTemplateResponse.FromString,
        )
    self.GetTransport = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/GetTransport',
        request_serializer=logistics__pb2.GetTransportRequest.SerializeToString,
        response_deserializer=logistics__pb2.GetTransportResponse.FromString,
        )
    self.CreateTransport = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/CreateTransport',
        request_serializer=logistics__pb2.CreateTransportRequest.SerializeToString,
        response_deserializer=logistics__pb2.CreateTransportResponse.FromString,
        )
    self.DeleteTransport = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/DeleteTransport',
        request_serializer=logistics__pb2.DeleteTransportRequest.SerializeToString,
        response_deserializer=logistics__pb2.DeleteTransportResponse.FromString,
        )
    self.ListTransports = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/ListTransports',
        request_serializer=logistics__pb2.ListTransportsRequest.SerializeToString,
        response_deserializer=logistics__pb2.ListTransportsResponse.FromString,
        )
    self.GetTransportOfferState = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/GetTransportOfferState',
        request_serializer=logistics__pb2.GetDataOfferStateRequest.SerializeToString,
        response_deserializer=logistics__pb2.GetDataOfferStateResponse.FromString,
        )
    self.UpdateTransportOfferState = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/UpdateTransportOfferState',
        request_serializer=logistics__pb2.UpdateDataOfferStateRequest.SerializeToString,
        response_deserializer=logistics__pb2.UpdateDataOfferStateResponse.FromString,
        )
    self.DeleteTransportOfferState = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/DeleteTransportOfferState',
        request_serializer=logistics__pb2.DeleteDataOfferStateRequest.SerializeToString,
        response_deserializer=logistics__pb2.DeleteDataOfferStateResponse.FromString,
        )
    self.ListTransportOfferStates = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/ListTransportOfferStates',
        request_serializer=logistics__pb2.ListDataOfferStatesRequest.SerializeToString,
        response_deserializer=logistics__pb2.ListDataOfferStatesResponse.FromString,
        )
    self.GetDataOfferState = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/GetDataOfferState',
        request_serializer=logistics__pb2.GetDataOfferStateRequest.SerializeToString,
        response_deserializer=logistics__pb2.GetDataOfferStateResponse.FromString,
        )
    self.UpdateDataOfferState = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/UpdateDataOfferState',
        request_serializer=logistics__pb2.UpdateDataOfferStateRequest.SerializeToString,
        response_deserializer=logistics__pb2.UpdateDataOfferStateResponse.FromString,
        )
    self.DeleteDataOfferState = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/DeleteDataOfferState',
        request_serializer=logistics__pb2.DeleteDataOfferStateRequest.SerializeToString,
        response_deserializer=logistics__pb2.DeleteDataOfferStateResponse.FromString,
        )
    self.ListDataOfferStates = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/ListDataOfferStates',
        request_serializer=logistics__pb2.ListDataOfferStatesRequest.SerializeToString,
        response_deserializer=logistics__pb2.ListDataOfferStatesResponse.FromString,
        )
    self.SaveDataOfferState = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/SaveDataOfferState',
        request_serializer=logistics__pb2.SaveDataOfferStateRequest.SerializeToString,
        response_deserializer=logistics__pb2.SaveDataOfferStateResponse.FromString,
        )
    self.SearchDataOfferStates = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/SearchDataOfferStates',
        request_serializer=logistics__pb2.SearchDataOfferStatesRequest.SerializeToString,
        response_deserializer=logistics__pb2.SearchDataOfferStatesResponse.FromString,
        )
    self.SearchTransportOfferStates = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/SearchTransportOfferStates',
        request_serializer=logistics__pb2.SearchDataOfferStatesRequest.SerializeToString,
        response_deserializer=logistics__pb2.SearchDataOfferStatesResponse.FromString,
        )
    self.GetDataSubscriptionState = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/GetDataSubscriptionState',
        request_serializer=logistics__pb2.GetDataSubscriptionStateRequest.SerializeToString,
        response_deserializer=logistics__pb2.GetDataSubscriptionStateResponse.FromString,
        )
    self.DeleteDataSubscriptionState = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/DeleteDataSubscriptionState',
        request_serializer=logistics__pb2.DeleteDataSubscriptionStateRequest.SerializeToString,
        response_deserializer=logistics__pb2.DeleteDataSubscriptionStateResponse.FromString,
        )
    self.ListDataSubscriptionStates = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/ListDataSubscriptionStates',
        request_serializer=logistics__pb2.ListDataSubscriptionStatesRequest.SerializeToString,
        response_deserializer=logistics__pb2.ListDataSubscriptionStatesResponse.FromString,
        )
    self.SaveDataSubscriptionState = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/SaveDataSubscriptionState',
        request_serializer=logistics__pb2.SaveDataSubscriptionStateRequest.SerializeToString,
        response_deserializer=logistics__pb2.SaveDataSubscriptionStateResponse.FromString,
        )
    self.SearchDataSubscriptionStates = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/SearchDataSubscriptionStates',
        request_serializer=logistics__pb2.SearchDataSubscriptionStatesRequest.SerializeToString,
        response_deserializer=logistics__pb2.SearchDataSubscriptionStatesResponse.FromString,
        )
    self.GetHistory = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/GetHistory',
        request_serializer=logistics__pb2.GetHistoryRequest.SerializeToString,
        response_deserializer=logistics__pb2.GetHistoryResponse.FromString,
        )
    self.GetNamespace = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/GetNamespace',
        request_serializer=resource__group__pb2.GetResourceGroupRequest.SerializeToString,
        response_deserializer=resource__group__pb2.GetResourceGroupResponse.FromString,
        )
    self.UpdateNamespace = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/UpdateNamespace',
        request_serializer=resource__group__pb2.UpdateResourceGroupRequest.SerializeToString,
        response_deserializer=resource__group__pb2.UpdateResourceGroupResponse.FromString,
        )
    self.CreateNamespace = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/CreateNamespace',
        request_serializer=resource__group__pb2.CreateResourceGroupRequest.SerializeToString,
        response_deserializer=resource__group__pb2.CreateResourceGroupResponse.FromString,
        )
    self.DeleteNamespace = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/DeleteNamespace',
        request_serializer=resource__group__pb2.DeleteResourceGroupRequest.SerializeToString,
        response_deserializer=resource__group__pb2.DeleteResourceGroupResponse.FromString,
        )
    self.ListNamespaces = channel.unary_unary(
        '/io.spoud.sdm.logistics.v1.Logistics/ListNamespaces',
        request_serializer=resource__group__pb2.ListResourceGroupsRequest.SerializeToString,
        response_deserializer=resource__group__pb2.ListResourceGroupsResponse.FromString,
        )


class LogisticsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateOffer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteOffer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetOffer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListOffers(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateOffer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SearchDataOffers(self, request, context):
    """<b>EXPERIMENTAL</b>
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateSubscription(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteSubscription(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSubscription(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListSubscriptions(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateSubscription(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateConnector(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteConnector(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetConnector(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListConnectors(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateConnector(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateGroup(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteGroup(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetGroup(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListGroups(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateGroup(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateOfferTemplate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteOfferTemplate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetOfferTemplate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListOfferTemplates(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateOfferTemplate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateSubscriptionTemplate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteSubscriptionTemplate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSubscriptionTemplate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListSubscriptionTemplates(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateSubscriptionTemplate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTransport(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateTransport(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteTransport(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListTransports(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTransportOfferState(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateTransportOfferState(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteTransportOfferState(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListTransportOfferStates(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDataOfferState(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateDataOfferState(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteDataOfferState(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListDataOfferStates(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SaveDataOfferState(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SearchDataOfferStates(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SearchTransportOfferStates(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDataSubscriptionState(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteDataSubscriptionState(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListDataSubscriptionStates(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SaveDataSubscriptionState(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SearchDataSubscriptionStates(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetHistory(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetNamespace(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateNamespace(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateNamespace(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteNamespace(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListNamespaces(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_LogisticsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateOffer': grpc.unary_unary_rpc_method_handler(
          servicer.CreateOffer,
          request_deserializer=logistics__pb2.CreateDataOfferRequest.FromString,
          response_serializer=logistics__pb2.CreateDataOfferResponse.SerializeToString,
      ),
      'DeleteOffer': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteOffer,
          request_deserializer=logistics__pb2.DeleteDataOfferRequest.FromString,
          response_serializer=logistics__pb2.DeleteDataOfferResponse.SerializeToString,
      ),
      'GetOffer': grpc.unary_unary_rpc_method_handler(
          servicer.GetOffer,
          request_deserializer=logistics__pb2.GetDataOfferRequest.FromString,
          response_serializer=logistics__pb2.GetDataOfferResponse.SerializeToString,
      ),
      'ListOffers': grpc.unary_unary_rpc_method_handler(
          servicer.ListOffers,
          request_deserializer=logistics__pb2.ListDataOffersRequest.FromString,
          response_serializer=logistics__pb2.ListDataOffersResponse.SerializeToString,
      ),
      'UpdateOffer': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateOffer,
          request_deserializer=logistics__pb2.UpdateDataOfferRequest.FromString,
          response_serializer=logistics__pb2.UpdateDataOfferResponse.SerializeToString,
      ),
      'SearchDataOffers': grpc.unary_unary_rpc_method_handler(
          servicer.SearchDataOffers,
          request_deserializer=logistics__pb2.SearchDataOffersRequest.FromString,
          response_serializer=logistics__pb2.SearchDataOffersResponse.SerializeToString,
      ),
      'CreateSubscription': grpc.unary_unary_rpc_method_handler(
          servicer.CreateSubscription,
          request_deserializer=logistics__pb2.CreateDataSubscriptionRequest.FromString,
          response_serializer=logistics__pb2.CreateDataSubscriptionResponse.SerializeToString,
      ),
      'DeleteSubscription': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteSubscription,
          request_deserializer=logistics__pb2.DeleteDataSubscriptionRequest.FromString,
          response_serializer=logistics__pb2.DeleteDataSubscriptionResponse.SerializeToString,
      ),
      'GetSubscription': grpc.unary_unary_rpc_method_handler(
          servicer.GetSubscription,
          request_deserializer=logistics__pb2.GetDataSubscriptionRequest.FromString,
          response_serializer=logistics__pb2.GetDataSubscriptionResponse.SerializeToString,
      ),
      'ListSubscriptions': grpc.unary_unary_rpc_method_handler(
          servicer.ListSubscriptions,
          request_deserializer=logistics__pb2.ListDataSubscriptionsRequest.FromString,
          response_serializer=logistics__pb2.ListDataSubscriptionsResponse.SerializeToString,
      ),
      'UpdateSubscription': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateSubscription,
          request_deserializer=logistics__pb2.UpdateDataSubscriptionRequest.FromString,
          response_serializer=logistics__pb2.UpdateDataSubscriptionResponse.SerializeToString,
      ),
      'CreateConnector': grpc.unary_unary_rpc_method_handler(
          servicer.CreateConnector,
          request_deserializer=logistics__pb2.CreateConnectorRequest.FromString,
          response_serializer=logistics__pb2.CreateConnectorResponse.SerializeToString,
      ),
      'DeleteConnector': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteConnector,
          request_deserializer=logistics__pb2.DeleteConnectorRequest.FromString,
          response_serializer=logistics__pb2.DeleteConnectorResponse.SerializeToString,
      ),
      'GetConnector': grpc.unary_unary_rpc_method_handler(
          servicer.GetConnector,
          request_deserializer=logistics__pb2.GetConnectorRequest.FromString,
          response_serializer=logistics__pb2.GetConnectorResponse.SerializeToString,
      ),
      'ListConnectors': grpc.unary_unary_rpc_method_handler(
          servicer.ListConnectors,
          request_deserializer=logistics__pb2.ListConnectorsRequest.FromString,
          response_serializer=logistics__pb2.ListConnectorsResponse.SerializeToString,
      ),
      'UpdateConnector': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateConnector,
          request_deserializer=logistics__pb2.UpdateConnectorRequest.FromString,
          response_serializer=logistics__pb2.UpdateConnectorResponse.SerializeToString,
      ),
      'CreateGroup': grpc.unary_unary_rpc_method_handler(
          servicer.CreateGroup,
          request_deserializer=logistics__pb2.CreateGroupRequest.FromString,
          response_serializer=logistics__pb2.CreateGroupResponse.SerializeToString,
      ),
      'DeleteGroup': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteGroup,
          request_deserializer=logistics__pb2.DeleteGroupRequest.FromString,
          response_serializer=logistics__pb2.DeleteGroupResponse.SerializeToString,
      ),
      'GetGroup': grpc.unary_unary_rpc_method_handler(
          servicer.GetGroup,
          request_deserializer=logistics__pb2.GetGroupRequest.FromString,
          response_serializer=logistics__pb2.GetGroupResponse.SerializeToString,
      ),
      'ListGroups': grpc.unary_unary_rpc_method_handler(
          servicer.ListGroups,
          request_deserializer=logistics__pb2.ListGroupsRequest.FromString,
          response_serializer=logistics__pb2.ListGroupsResponse.SerializeToString,
      ),
      'UpdateGroup': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateGroup,
          request_deserializer=logistics__pb2.UpdateGroupRequest.FromString,
          response_serializer=logistics__pb2.UpdateGroupResponse.SerializeToString,
      ),
      'CreateOfferTemplate': grpc.unary_unary_rpc_method_handler(
          servicer.CreateOfferTemplate,
          request_deserializer=logistics__pb2.CreateDataOfferTemplateRequest.FromString,
          response_serializer=logistics__pb2.CreateDataOfferTemplateResponse.SerializeToString,
      ),
      'DeleteOfferTemplate': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteOfferTemplate,
          request_deserializer=logistics__pb2.DeleteDataOfferTemplateRequest.FromString,
          response_serializer=logistics__pb2.DeleteDataOfferTemplateResponse.SerializeToString,
      ),
      'GetOfferTemplate': grpc.unary_unary_rpc_method_handler(
          servicer.GetOfferTemplate,
          request_deserializer=logistics__pb2.GetDataOfferTemplateRequest.FromString,
          response_serializer=logistics__pb2.GetDataOfferTemplateResponse.SerializeToString,
      ),
      'ListOfferTemplates': grpc.unary_unary_rpc_method_handler(
          servicer.ListOfferTemplates,
          request_deserializer=logistics__pb2.ListDataOfferTemplatesRequest.FromString,
          response_serializer=logistics__pb2.ListDataOfferTemplatesResponse.SerializeToString,
      ),
      'UpdateOfferTemplate': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateOfferTemplate,
          request_deserializer=logistics__pb2.UpdateDataOfferTemplateRequest.FromString,
          response_serializer=logistics__pb2.UpdateDataOfferTemplateResponse.SerializeToString,
      ),
      'CreateSubscriptionTemplate': grpc.unary_unary_rpc_method_handler(
          servicer.CreateSubscriptionTemplate,
          request_deserializer=logistics__pb2.CreateDataSubscriptionTemplateRequest.FromString,
          response_serializer=logistics__pb2.CreateDataSubscriptionTemplateResponse.SerializeToString,
      ),
      'DeleteSubscriptionTemplate': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteSubscriptionTemplate,
          request_deserializer=logistics__pb2.DeleteDataSubscriptionTemplateRequest.FromString,
          response_serializer=logistics__pb2.DeleteDataSubscriptionTemplateResponse.SerializeToString,
      ),
      'GetSubscriptionTemplate': grpc.unary_unary_rpc_method_handler(
          servicer.GetSubscriptionTemplate,
          request_deserializer=logistics__pb2.GetDataSubscriptionTemplateRequest.FromString,
          response_serializer=logistics__pb2.GetDataSubscriptionTemplateResponse.SerializeToString,
      ),
      'ListSubscriptionTemplates': grpc.unary_unary_rpc_method_handler(
          servicer.ListSubscriptionTemplates,
          request_deserializer=logistics__pb2.ListDataSubscriptionTemplatesRequest.FromString,
          response_serializer=logistics__pb2.ListDataSubscriptionTemplatesResponse.SerializeToString,
      ),
      'UpdateSubscriptionTemplate': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateSubscriptionTemplate,
          request_deserializer=logistics__pb2.UpdateDataSubscriptionTemplateRequest.FromString,
          response_serializer=logistics__pb2.UpdateDataSubscriptionTemplateResponse.SerializeToString,
      ),
      'GetTransport': grpc.unary_unary_rpc_method_handler(
          servicer.GetTransport,
          request_deserializer=logistics__pb2.GetTransportRequest.FromString,
          response_serializer=logistics__pb2.GetTransportResponse.SerializeToString,
      ),
      'CreateTransport': grpc.unary_unary_rpc_method_handler(
          servicer.CreateTransport,
          request_deserializer=logistics__pb2.CreateTransportRequest.FromString,
          response_serializer=logistics__pb2.CreateTransportResponse.SerializeToString,
      ),
      'DeleteTransport': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteTransport,
          request_deserializer=logistics__pb2.DeleteTransportRequest.FromString,
          response_serializer=logistics__pb2.DeleteTransportResponse.SerializeToString,
      ),
      'ListTransports': grpc.unary_unary_rpc_method_handler(
          servicer.ListTransports,
          request_deserializer=logistics__pb2.ListTransportsRequest.FromString,
          response_serializer=logistics__pb2.ListTransportsResponse.SerializeToString,
      ),
      'GetTransportOfferState': grpc.unary_unary_rpc_method_handler(
          servicer.GetTransportOfferState,
          request_deserializer=logistics__pb2.GetDataOfferStateRequest.FromString,
          response_serializer=logistics__pb2.GetDataOfferStateResponse.SerializeToString,
      ),
      'UpdateTransportOfferState': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateTransportOfferState,
          request_deserializer=logistics__pb2.UpdateDataOfferStateRequest.FromString,
          response_serializer=logistics__pb2.UpdateDataOfferStateResponse.SerializeToString,
      ),
      'DeleteTransportOfferState': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteTransportOfferState,
          request_deserializer=logistics__pb2.DeleteDataOfferStateRequest.FromString,
          response_serializer=logistics__pb2.DeleteDataOfferStateResponse.SerializeToString,
      ),
      'ListTransportOfferStates': grpc.unary_unary_rpc_method_handler(
          servicer.ListTransportOfferStates,
          request_deserializer=logistics__pb2.ListDataOfferStatesRequest.FromString,
          response_serializer=logistics__pb2.ListDataOfferStatesResponse.SerializeToString,
      ),
      'GetDataOfferState': grpc.unary_unary_rpc_method_handler(
          servicer.GetDataOfferState,
          request_deserializer=logistics__pb2.GetDataOfferStateRequest.FromString,
          response_serializer=logistics__pb2.GetDataOfferStateResponse.SerializeToString,
      ),
      'UpdateDataOfferState': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateDataOfferState,
          request_deserializer=logistics__pb2.UpdateDataOfferStateRequest.FromString,
          response_serializer=logistics__pb2.UpdateDataOfferStateResponse.SerializeToString,
      ),
      'DeleteDataOfferState': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteDataOfferState,
          request_deserializer=logistics__pb2.DeleteDataOfferStateRequest.FromString,
          response_serializer=logistics__pb2.DeleteDataOfferStateResponse.SerializeToString,
      ),
      'ListDataOfferStates': grpc.unary_unary_rpc_method_handler(
          servicer.ListDataOfferStates,
          request_deserializer=logistics__pb2.ListDataOfferStatesRequest.FromString,
          response_serializer=logistics__pb2.ListDataOfferStatesResponse.SerializeToString,
      ),
      'SaveDataOfferState': grpc.unary_unary_rpc_method_handler(
          servicer.SaveDataOfferState,
          request_deserializer=logistics__pb2.SaveDataOfferStateRequest.FromString,
          response_serializer=logistics__pb2.SaveDataOfferStateResponse.SerializeToString,
      ),
      'SearchDataOfferStates': grpc.unary_unary_rpc_method_handler(
          servicer.SearchDataOfferStates,
          request_deserializer=logistics__pb2.SearchDataOfferStatesRequest.FromString,
          response_serializer=logistics__pb2.SearchDataOfferStatesResponse.SerializeToString,
      ),
      'SearchTransportOfferStates': grpc.unary_unary_rpc_method_handler(
          servicer.SearchTransportOfferStates,
          request_deserializer=logistics__pb2.SearchDataOfferStatesRequest.FromString,
          response_serializer=logistics__pb2.SearchDataOfferStatesResponse.SerializeToString,
      ),
      'GetDataSubscriptionState': grpc.unary_unary_rpc_method_handler(
          servicer.GetDataSubscriptionState,
          request_deserializer=logistics__pb2.GetDataSubscriptionStateRequest.FromString,
          response_serializer=logistics__pb2.GetDataSubscriptionStateResponse.SerializeToString,
      ),
      'DeleteDataSubscriptionState': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteDataSubscriptionState,
          request_deserializer=logistics__pb2.DeleteDataSubscriptionStateRequest.FromString,
          response_serializer=logistics__pb2.DeleteDataSubscriptionStateResponse.SerializeToString,
      ),
      'ListDataSubscriptionStates': grpc.unary_unary_rpc_method_handler(
          servicer.ListDataSubscriptionStates,
          request_deserializer=logistics__pb2.ListDataSubscriptionStatesRequest.FromString,
          response_serializer=logistics__pb2.ListDataSubscriptionStatesResponse.SerializeToString,
      ),
      'SaveDataSubscriptionState': grpc.unary_unary_rpc_method_handler(
          servicer.SaveDataSubscriptionState,
          request_deserializer=logistics__pb2.SaveDataSubscriptionStateRequest.FromString,
          response_serializer=logistics__pb2.SaveDataSubscriptionStateResponse.SerializeToString,
      ),
      'SearchDataSubscriptionStates': grpc.unary_unary_rpc_method_handler(
          servicer.SearchDataSubscriptionStates,
          request_deserializer=logistics__pb2.SearchDataSubscriptionStatesRequest.FromString,
          response_serializer=logistics__pb2.SearchDataSubscriptionStatesResponse.SerializeToString,
      ),
      'GetHistory': grpc.unary_unary_rpc_method_handler(
          servicer.GetHistory,
          request_deserializer=logistics__pb2.GetHistoryRequest.FromString,
          response_serializer=logistics__pb2.GetHistoryResponse.SerializeToString,
      ),
      'GetNamespace': grpc.unary_unary_rpc_method_handler(
          servicer.GetNamespace,
          request_deserializer=resource__group__pb2.GetResourceGroupRequest.FromString,
          response_serializer=resource__group__pb2.GetResourceGroupResponse.SerializeToString,
      ),
      'UpdateNamespace': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateNamespace,
          request_deserializer=resource__group__pb2.UpdateResourceGroupRequest.FromString,
          response_serializer=resource__group__pb2.UpdateResourceGroupResponse.SerializeToString,
      ),
      'CreateNamespace': grpc.unary_unary_rpc_method_handler(
          servicer.CreateNamespace,
          request_deserializer=resource__group__pb2.CreateResourceGroupRequest.FromString,
          response_serializer=resource__group__pb2.CreateResourceGroupResponse.SerializeToString,
      ),
      'DeleteNamespace': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteNamespace,
          request_deserializer=resource__group__pb2.DeleteResourceGroupRequest.FromString,
          response_serializer=resource__group__pb2.DeleteResourceGroupResponse.SerializeToString,
      ),
      'ListNamespaces': grpc.unary_unary_rpc_method_handler(
          servicer.ListNamespaces,
          request_deserializer=resource__group__pb2.ListResourceGroupsRequest.FromString,
          response_serializer=resource__group__pb2.ListResourceGroupsResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'io.spoud.sdm.logistics.v1.Logistics', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
